from __future__ import annotations
from pathlib import Path
from typing import Any
import sqlite3
from evidence_store_common import _now, _json, _stable_id, MIGRATIONS

class EvidenceStoreAnalysis:
    def replace_intelligence(self, *, run_id: str, video_rows: list[dict[str, Any]], creator_rows: list[dict[str, Any]], comment_rows: list[dict[str, Any]], findings: list[dict[str, Any]]) -> None:
        now=_now()
        for table in ('video_metrics_derived','creator_metrics_derived','comment_labels','findings'): self.conn.execute(f'DELETE FROM {table} WHERE run_id=?',(run_id,))
        for row in video_rows:self.conn.execute('INSERT INTO video_metrics_derived(run_id,video_id,engagement_rate,like_rate,comment_rate,share_rate,save_rate,follower_leverage,view_velocity_per_hour,like_velocity_per_hour,comment_velocity_per_hour,views_percentile,engagement_percentile,share_rate_percentile,follower_leverage_percentile,creator_overperformance,creator_baseline_views,creator_baseline_sample,cohort_json,evidence_refs_json,computed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(run_id,row.get('video_id'),row.get('engagement_rate'),row.get('like_rate'),row.get('comment_rate'),row.get('share_rate'),row.get('save_rate'),row.get('follower_leverage'),row.get('view_velocity_per_hour'),row.get('like_velocity_per_hour'),row.get('comment_velocity_per_hour'),row.get('views_percentile'),row.get('engagement_percentile'),row.get('share_rate_percentile'),row.get('follower_leverage_percentile'),row.get('creator_overperformance'),row.get('creator_baseline_views'),row.get('creator_baseline_sample'),_json({'cohorts':row.get('cohorts') or {},'percentiles':row.get('cohort_percentiles') or {}}),_json(row.get('evidence_refs') or []),now))
        for row in creator_rows:self.conn.execute('INSERT INTO creator_metrics_derived(run_id,creator_id,baseline_views,sample_size,median_engagement_rate,evidence_refs_json,computed_at) VALUES(?,?,?,?,?,?,?)',(run_id,row.get('creator_id'),row.get('baseline_views'),row.get('sample_size') or 0,row.get('median_engagement_rate'),_json(row.get('evidence_refs') or []),now))
        for row in comment_rows:self.conn.execute('INSERT INTO comment_labels(run_id,comment_id,labels_json,matched_terms_json,weighted_intensity,classifier_version,evidence_refs_json,computed_at) VALUES(?,?,?,?,?,?,?,?)',(run_id,row.get('comment_id'),_json(row.get('labels') or []),_json(row.get('matched_terms') or {}),float(row.get('weighted_intensity') or 0.0),row.get('classifier_version') or 'unknown',_json(row.get('evidence_refs') or []),now))
        for row in findings:self.conn.execute('INSERT INTO findings(id,run_id,finding_type,category,statement,evidence_refs_json,metrics_json,support_count,created_at) VALUES(?,?,?,?,?,?,?,?,?)',(row.get('id'),run_id,row.get('finding_type'),row.get('category'),row.get('statement'),_json(row.get('evidence_refs') or []),_json(row.get('metrics') or {}),int(row.get('support_count') or 0),now))
        self.conn.commit()
    def upsert_creative_analysis(self, run_id: str, row: dict[str, Any]) -> None:
        analyzer=row.get('analyzer') or {}; self.conn.execute('INSERT INTO creative_analysis(run_id,video_id,schema_version,analyzer_name,analyzer_version,analyzer_mode,hook_type,hook_text,product_visible_at,format,selling_angle,proof_type,cta_text,cta_at,shot_count,avg_shot_length,visual_style,timeline_json,confidence_json,evidence_refs_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id,video_id,analyzer_name) DO UPDATE SET schema_version=excluded.schema_version,analyzer_version=excluded.analyzer_version,analyzer_mode=excluded.analyzer_mode,hook_type=excluded.hook_type,hook_text=excluded.hook_text,product_visible_at=excluded.product_visible_at,format=excluded.format,selling_angle=excluded.selling_angle,proof_type=excluded.proof_type,cta_text=excluded.cta_text,cta_at=excluded.cta_at,shot_count=excluded.shot_count,avg_shot_length=excluded.avg_shot_length,visual_style=excluded.visual_style,timeline_json=excluded.timeline_json,confidence_json=excluded.confidence_json,evidence_refs_json=excluded.evidence_refs_json,created_at=excluded.created_at',(run_id,row.get('video_id'),row.get('schema_version') or '1.0',analyzer.get('name') or 'unknown',analyzer.get('version'),analyzer.get('mode') or 'unknown',row.get('hook_type'),row.get('hook_text'),row.get('product_visible_at'),row.get('format'),row.get('selling_angle'),row.get('proof_type'),row.get('cta_text'),row.get('cta_at'),row.get('shot_count'),row.get('avg_shot_length'),row.get('visual_style'),_json(row.get('timeline') or []),_json(row.get('confidence') or {}),_json(row.get('evidence_refs') or []),_now())); self.conn.commit()
    def replace_media_analysis(self, *, run_id: str, video_id: str, asset: dict[str, Any] | None=None, keyframes: list[dict[str, Any]] | None=None, transcripts: list[dict[str, Any]] | None=None) -> None:
        now=_now(); self.conn.execute('DELETE FROM media_keyframes WHERE run_id=? AND video_id=?',(run_id,video_id)); self.conn.execute('DELETE FROM transcript_segments WHERE run_id=? AND video_id=?',(run_id,video_id))
        if asset is not None:self.conn.execute('INSERT INTO media_assets(run_id,video_id,source_url,local_path,sha256,byte_size,duration_sec,width,height,fps,status,error,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id,video_id) DO UPDATE SET source_url=excluded.source_url,local_path=excluded.local_path,sha256=excluded.sha256,byte_size=excluded.byte_size,duration_sec=excluded.duration_sec,width=excluded.width,height=excluded.height,fps=excluded.fps,status=excluded.status,error=excluded.error,created_at=excluded.created_at',(run_id,video_id,asset.get('source_url'),asset.get('local_path'),asset.get('sha256'),asset.get('byte_size'),asset.get('duration_sec'),asset.get('width'),asset.get('height'),asset.get('fps'),asset.get('status') or 'unknown',asset.get('error'),now))
        for index,frame in enumerate(keyframes or []):
            frame_id=frame.get('id') or _stable_id(run_id,video_id,'frame',index,frame.get('timestamp_sec')); self.conn.execute('INSERT INTO media_keyframes(id,run_id,video_id,timestamp_sec,local_path,scene_index,ocr_text,ocr_confidence,evidence_refs_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',(frame_id,run_id,video_id,frame.get('timestamp_sec') or 0.0,frame.get('path') or frame.get('local_path'),frame.get('scene_index'),frame.get('ocr_text'),frame.get('ocr_confidence'),_json(frame.get('evidence_refs') or []),now))
        for index,seg in enumerate(transcripts or []):
            seg_id=seg.get('id') or _stable_id(run_id,video_id,'transcript',index,seg.get('start_sec'),seg.get('text')); self.conn.execute('INSERT INTO transcript_segments(id,run_id,video_id,start_sec,end_sec,text,source,confidence,evidence_refs_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',(seg_id,run_id,video_id,seg.get('start_sec'),seg.get('end_sec'),seg.get('text') or '',seg.get('source') or 'unknown',seg.get('confidence'),_json(seg.get('evidence_refs') or []),now))
        self.conn.commit()
    def replace_patterns(self, run_id: str, rows: list[dict[str, Any]]) -> None:
        now=_now(); self.conn.execute('DELETE FROM creative_patterns WHERE run_id=?',(run_id,))
        for row in rows:self.conn.execute('INSERT INTO creative_patterns(id,run_id,performance_metric,pattern_field,pattern_value,top_cohort_size,baseline_size,top_support,baseline_support,top_share,baseline_share,lift,creator_support,organic_support,ad_support,evidence_refs_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(row.get('id'),run_id,row.get('performance_metric'),row.get('pattern_field'),row.get('pattern_value'),int(row.get('top_cohort_size') or 0),int(row.get('baseline_size') or 0),int(row.get('top_support') or 0),int(row.get('baseline_support') or 0),float(row.get('top_share') or 0.0),float(row.get('baseline_share') or 0.0),row.get('lift'),int(row.get('creator_support') or 0),int(row.get('organic_support') or 0),int(row.get('ad_support') or 0),_json(row.get('evidence_refs') or []),now))
        self.conn.commit()
    def replace_semantic_outputs(self, run_id: str, payload: dict[str, Any]) -> None:
        analyzer=payload.get('analyzer') or {}; now=_now()
        for table in ('insights','creative_hypotheses','media_briefs'):self.conn.execute(f'DELETE FROM {table} WHERE run_id=?',(run_id,))
        for row in payload.get('insights') or []:self.conn.execute('INSERT INTO insights(id,run_id,statement,evidence_refs_json,confidence,analyzer_name,analyzer_version,analyzer_mode,created_at) VALUES(?,?,?,?,?,?,?,?,?)',(row.get('id'),run_id,row.get('statement'),_json(row.get('evidence_refs') or []),float(row.get('confidence')),analyzer.get('name'),analyzer.get('version'),analyzer.get('mode'),now))
        for row in payload.get('hypotheses') or []:self.conn.execute('INSERT INTO creative_hypotheses(id,run_id,statement,objective,hook_type,format,selling_angle,proof_type,evidence_refs_json,confidence,status,analyzer_name,analyzer_version,analyzer_mode,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(row.get('id'),run_id,row.get('statement'),row.get('objective'),row.get('hook_type'),row.get('format'),row.get('selling_angle'),row.get('proof_type'),_json(row.get('evidence_refs') or []),float(row.get('confidence')),row.get('status') or 'PROPOSED',analyzer.get('name'),analyzer.get('version'),analyzer.get('mode'),now))
        for row in payload.get('media_briefs') or []:self.conn.execute('INSERT INTO media_briefs(id,run_id,hypothesis_id,objective,target_audience,duration_target_sec,timeline_json,cta,evidence_refs_json,confidence,analyzer_name,analyzer_version,analyzer_mode,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(row.get('id'),run_id,row.get('hypothesis_id'),row.get('objective'),row.get('target_audience'),row.get('duration_target_sec'),_json(row.get('timeline') or []),row.get('cta'),_json(row.get('evidence_refs') or []),float(row.get('confidence')),analyzer.get('name'),analyzer.get('version'),analyzer.get('mode'),now))
        self.conn.commit()
