from __future__ import annotations
from pathlib import Path
from typing import Any
import sqlite3
from evidence_store_common import _now, _json, _stable_id, MIGRATIONS

class EvidenceStoreCore:
    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.conn = sqlite3.connect(self.path)
        self.conn.execute('PRAGMA foreign_keys = ON')
        for migration in MIGRATIONS:
            self.conn.executescript(migration.read_text(encoding='utf-8'))
        self.conn.commit()
    def close(self) -> None:
        self.conn.commit(); self.conn.close()
    def table_names(self) -> list[str]:
        return [row[0] for row in self.conn.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")]
    def record_run(self, run_id: str, request_payload: dict[str, Any], profile_id: str, provider: str, status: str='running') -> None:
        self.conn.execute('INSERT INTO research_runs(id, request_json, profile_id, provider, status, started_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET request_json=excluded.request_json, profile_id=excluded.profile_id, provider=excluded.provider, status=excluded.status',(run_id,_json(request_payload),profile_id,provider,status,_now())); self.conn.commit()
    def finish_run(self, run_id: str, status: str) -> None:
        self.conn.execute('UPDATE research_runs SET status=?, completed_at=? WHERE id=?',(status,_now(),run_id)); self.conn.commit()
    def record_raw_evidence(self, *, evidence_id: str, run_id: str, endpoint: str, method: str, request_payload: Any, response_payload: Any, source_type: str | None=None, source_key: str | None=None) -> None:
        self.conn.execute('INSERT OR REPLACE INTO raw_evidence (id,run_id,endpoint,method,request_json,response_json,source_type,source_key,fetched_at) VALUES(?,?,?,?,?,?,?,?,?)',(evidence_id,run_id,endpoint,method,_json(request_payload),_json(response_payload),source_type,source_key,_now())); self.conn.commit()
    def persist_bundle(self, bundle: dict[str, list[dict[str, Any]]], *, run_id: str) -> None:
        now=_now()
        for row in bundle.get('creators',[]):
            self.conn.execute('INSERT INTO creators(creator_id,sec_user_id,unique_id,nickname,bio,region,verified,followers,following,total_likes,video_count,last_seen_at,raw_evidence_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(creator_id) DO UPDATE SET sec_user_id=COALESCE(excluded.sec_user_id,creators.sec_user_id),unique_id=COALESCE(excluded.unique_id,creators.unique_id),nickname=COALESCE(excluded.nickname,creators.nickname),bio=COALESCE(excluded.bio,creators.bio),region=COALESCE(excluded.region,creators.region),verified=excluded.verified,followers=COALESCE(excluded.followers,creators.followers),following=COALESCE(excluded.following,creators.following),total_likes=COALESCE(excluded.total_likes,creators.total_likes),video_count=COALESCE(excluded.video_count,creators.video_count),last_seen_at=excluded.last_seen_at,raw_evidence_id=excluded.raw_evidence_id',(row.get('creator_id'),row.get('sec_user_id'),row.get('unique_id'),row.get('nickname'),row.get('bio'),row.get('region'),row.get('verified'),row.get('followers'),row.get('following'),row.get('total_likes'),row.get('video_count'),now,row.get('raw_evidence_id')))
        for row in bundle.get('videos',[]):
            self.conn.execute('INSERT INTO videos(video_id,creator_id,caption,create_time,duration_sec,region,cover_url,video_url,music_id,music_title,hashtags_json,first_seen_at,last_seen_at,raw_evidence_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(video_id) DO UPDATE SET creator_id=COALESCE(excluded.creator_id,videos.creator_id),caption=COALESCE(excluded.caption,videos.caption),create_time=COALESCE(excluded.create_time,videos.create_time),duration_sec=COALESCE(excluded.duration_sec,videos.duration_sec),region=COALESCE(excluded.region,videos.region),cover_url=COALESCE(excluded.cover_url,videos.cover_url),video_url=COALESCE(excluded.video_url,videos.video_url),music_id=COALESCE(excluded.music_id,videos.music_id),music_title=COALESCE(excluded.music_title,videos.music_title),hashtags_json=COALESCE(excluded.hashtags_json,videos.hashtags_json),last_seen_at=excluded.last_seen_at,raw_evidence_id=excluded.raw_evidence_id',(row.get('video_id'),row.get('creator_id'),row.get('caption'),row.get('create_time'),row.get('duration_sec'),row.get('region'),row.get('cover_url'),row.get('video_url'),row.get('music_id'),row.get('music_title'),row.get('hashtags_json'),now,now,row.get('raw_evidence_id')))
        for row in bundle.get('video_snapshots',[]): self.conn.execute('INSERT INTO video_snapshots(run_id,video_id,views,likes,comments,shares,favorites,author_followers,captured_at,raw_evidence_id) VALUES(?,?,?,?,?,?,?,?,?,?)',(run_id,row.get('video_id'),row.get('views'),row.get('likes'),row.get('comments'),row.get('shares'),row.get('favorites'),row.get('author_followers'),now,row.get('raw_evidence_id')))
        for row in bundle.get('discoveries',[]):
            did=_stable_id(run_id,row.get('video_id'),row.get('source_type'),row.get('query_text'),row.get('sort_type'),row.get('time_window'),row.get('raw_evidence_id')); self.conn.execute('INSERT OR IGNORE INTO discoveries(id,run_id,video_id,source_type,query_text,source_rank,sort_type,time_window,discovered_at,raw_evidence_id) VALUES(?,?,?,?,?,?,?,?,?,?)',(did,run_id,row.get('video_id'),row.get('source_type') or 'unknown',row.get('query_text'),row.get('source_rank'),row.get('sort_type'),row.get('time_window'),now,row.get('raw_evidence_id')))
        for row in bundle.get('comments',[]): self.conn.execute('INSERT INTO comments(comment_id,video_id,author_id,text,like_count,reply_count,language,created_at,raw_evidence_id) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(comment_id) DO UPDATE SET video_id=COALESCE(excluded.video_id,comments.video_id),author_id=COALESCE(excluded.author_id,comments.author_id),text=excluded.text,like_count=COALESCE(excluded.like_count,comments.like_count),reply_count=COALESCE(excluded.reply_count,comments.reply_count),language=COALESCE(excluded.language,comments.language),created_at=COALESCE(excluded.created_at,comments.created_at),raw_evidence_id=excluded.raw_evidence_id',(row.get('comment_id'),row.get('video_id'),row.get('author_id'),row.get('text'),row.get('like_count'),row.get('reply_count'),row.get('language'),row.get('created_at'),row.get('raw_evidence_id')))
        for row in bundle.get('ads',[]): self.conn.execute('INSERT INTO ads(material_id,ads_id,video_id,ad_title,description,brand_name,advertiser_name,landing_page,industry_key,objective_key,cost_level,ctr_raw,likes,comments,shares,create_time,raw_evidence_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(material_id) DO UPDATE SET ads_id=COALESCE(excluded.ads_id,ads.ads_id),video_id=COALESCE(excluded.video_id,ads.video_id),ad_title=COALESCE(excluded.ad_title,ads.ad_title),description=COALESCE(excluded.description,ads.description),brand_name=COALESCE(excluded.brand_name,ads.brand_name),advertiser_name=COALESCE(excluded.advertiser_name,ads.advertiser_name),landing_page=COALESCE(excluded.landing_page,ads.landing_page),industry_key=COALESCE(excluded.industry_key,ads.industry_key),objective_key=COALESCE(excluded.objective_key,ads.objective_key),cost_level=COALESCE(excluded.cost_level,ads.cost_level),ctr_raw=COALESCE(excluded.ctr_raw,ads.ctr_raw),likes=COALESCE(excluded.likes,ads.likes),comments=COALESCE(excluded.comments,ads.comments),shares=COALESCE(excluded.shares,ads.shares),create_time=COALESCE(excluded.create_time,ads.create_time),raw_evidence_id=excluded.raw_evidence_id',(row.get('material_id'),row.get('ads_id'),row.get('video_id'),row.get('ad_title'),row.get('description'),row.get('brand_name'),row.get('advertiser_name'),row.get('landing_page'),row.get('industry_key'),row.get('objective_key'),row.get('cost_level'),row.get('ctr_raw'),row.get('likes'),row.get('comments'),row.get('shares'),row.get('create_time'),row.get('raw_evidence_id')))
        for row in bundle.get('ad_timeseries',[]):
            rid=_stable_id(run_id,row.get('material_id'),row.get('analysis_type'),row.get('metric'),row.get('second'),row.get('raw_evidence_id')); self.conn.execute('INSERT OR REPLACE INTO ad_timeseries(id,run_id,material_id,analysis_type,metric,second,value,is_drop,is_highlight,captured_at,raw_evidence_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)',(rid,run_id,row.get('material_id'),row.get('analysis_type'),row.get('metric'),row.get('second'),row.get('value'),row.get('is_drop',0),row.get('is_highlight',0),now,row.get('raw_evidence_id')))
        for row in bundle.get('search_insights',[]):
            rid=_stable_id(run_id,row.get('query_id'),row.get('insight_type'),row.get('raw_evidence_id')); self.conn.execute('INSERT OR REPLACE INTO search_insights(id,run_id,query_id,keyword,insight_type,region,language,rank,trend_json,demographics_json,raw_metrics_json,captured_at,raw_evidence_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',(rid,run_id,row.get('query_id'),row.get('keyword'),row.get('insight_type'),row.get('region'),row.get('language'),row.get('rank'),row.get('trend_json'),row.get('demographics_json'),row.get('raw_metrics_json'),now,row.get('raw_evidence_id')))
        self.conn.commit()
